apiVersion: v1
kind: PersistentVolume
metadata:
  name: pradeep-1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data/mysql"
