apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"] # which resource (noun)
  verbs: ["get", "list", "watch"] # what actions can be performed 
  # missing the who  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: pradeep-ns # add your namespace
subjects: # who    
- kind: User
  name: pradeep.kumar44@gmail.com  # add your email address
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader 
  apiGroup: rbac.authorization.k8s.io 
