apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["*"] # which resource (noun)
  verbs: ["get", "list", "watch", "create", "delete"] # what actions can be performed 
- apiGroups: ["apps"]
  resources: ["*"] # which resource (noun)
  verbs: ["list", "watch", "create", "delete"] # what actions can be performed 
  # missing the who  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: aditi-ns # add your namespace
subjects: # who    
- kind: User
  name: aditi@gmail.com  # add your email address
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader 
  apiGroup: rbac.authorization.k8s.io 
