apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-rwo
provisioner:  pd.csi.storage.gke.io
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
