apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-rwo
provisioner:  pd.csi.storage.gke.io
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pradeep-pvc-1
spec:
  storageClassName: custom-rwo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod-2
spec:
  containers:
  - name: debug-pod
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: debug-volume
      mountPath: /mnt
  volumes:
    - name: debug-volume
      persistentVolumeClaim:
        claimName: pradeep-pvc-1
  restartPolicy: Always


