apiVersion: v1
kind: ConfigMap
metadata:
  name: order-microservice-cm
data:
  application-dev.yaml: |-
    app:
      orderCount: 10
    server:
      port: 8222
    spring:
      datasource:
        url: jdbc:h2:mem:orders_db
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
            format_sql: true
      info:
        app:
          name: orders-api
          description: API for managing orders
          version: 1.0.0
      management:
        endpoint:
          health:
            show-details: "ALWAYS"
          circuitbreakers:
            enabled: true 
        endpoints:
          web:
            exposure:
              include: "*"
        info:
          env:
            enabled: true     
        health:
          probes:
            enabled: true  
  application-qa.yaml: |-
    app:
      orderCount: 10
    server:
      port: 8333
    spring:
      datasource:
        url: jdbc:h2:mem:orders_db
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
            format_sql: true
      info:
        app:
          name: orders-api
          description: API for managing orders
          version: 1.0.0
      management:
        endpoint:
          health:
            show-details: "ALWAYS"
          circuitbreakers:
            enabled: true 
        endpoints:
          web:
            exposure:
              include: "*"
        info:
          env:
            enabled: true     
        health:
          probes:
            enabled: true 
