apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/nginx/*.log
    output.console:
      enabled: true
      pretty: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
data:
  metricbeat.yml: |
    metricbeat.modules:
    - module: nginx
      metricsets: ["stubstatus"]
      hosts: ["http://nginx"]
      period: 10s
    output.console:
      enabled: true
      pretty: true
---      
